format = """\
[](fg:#1D3752)\
[ ](fg:#F7F0E0 bg:#1D3752)\
$conda\
[ ](fg:#1D3752 bg:#214D72)\
$directory\
[ ](fg:#214D72 bg:#2C7695)\
$git_branch\
$git_status\
$git_metrics\
[ ](fg:#2C7695 bg:#50BFC3)\
$python\
$cmd_duration\
[ ](fg:#50BFC3)\
$character\
"""

[conda]
style = "fg:#50BFC3 bg:#1D3752"
format = '[\($environment\)]($style)'

[directory]
format = "[  $path ]($style)"
style = "fg:#F7F0E0 bg:#214D72"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:#1D3752 bg:#2C7695"

[git_status]
format = '[\[$all_status\]]($style)'
style = "fg:#F7F0E0 bg:#2C7695"

[git_metrics]
format="([ +$added ]($added_style))([-$deleted ]($deleted_style))"
added_style = "fg:#B1D182 bg:#2C7695"
deleted_style = "fg:#C668AA bg:#2C7695"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[fill]
symbol = " "

[python]
format = "[ 󱔎 $version]($style)"
style = "fg:#1D3752 bg:#50BFC3"

[cmd_duration]
format = "[  $duration]($style)"
style = "fg:#214D72 bg:#50BFC3"

[character]
success_symbol = '[](fg:#B1D182)'
error_symbol = '[](fg:#F1485B)'

[username]
style_user = "bg:#00B7EB fg:00B7EB"
style_root = "bg:#00B7EB"
